### ISSUE TITLE
Isotype not found

### ISSUE THREAD

**Issue by arcolombo** [PENGLU-WashU/IMC_Denoise#10]
Hi, so when i use the jupyter notebook and download the supplementary table 5, and it says the metal is not found and i can not run the demo.  am I not pointing to the right directory?  

The channel names follow the "144Nd-CD14_Nd144.tiff"   format from the Zenodo deposit.    is there a issue to fix this?   is this a naming convention issue?

```
if 'generated_patches' in globals():
    del generated_patches
    
channel_name = "144Nd"
Raw_directory = "C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset/local-implementation-test" # change this directory to your Raw_image_directory.

Save_directory = None

n_neighbours = 4 # Larger n enables removing more consecutive hot pixels. 
n_iter = 3 # Iteration number for DIMR

DataGenerator = DeepSNiF_DataGenerator(channel_name = channel_name, n_neighbours = n_neighbours, n_iter = n_iter)
generated_patches = DataGenerator.generate_patches_from_directory(load_directory = Raw_directory)
if DataGenerator.save_patches(generated_patches, save_directory = Save_directory):
    print('Data generated successfully!')

```

**Comment by PENGLU-WashU** [comment]
> Hi, so when i use the jupyter notebook and download the supplementary table 5, and it says the metal is not found and i can not run the demo. am I not pointing to the right directory?
> 
> The channel names follow the "144Nd-CD14_Nd144.tiff" format from the Zenodo deposit. is there a issue to fix this? is this a naming convention issue?
> 
> ```
> if 'generated_patches' in globals():
>     del generated_patches
>     
> channel_name = "144Nd"
> Raw_directory = "C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset/local-implementation-test" # change this directory to your Raw_image_directory.
> 
> Save_directory = None
> 
> n_neighbours = 4 # Larger n enables removing more consecutive hot pixels. 
> n_iter = 3 # Iteration number for DIMR
> 
> DataGenerator = DeepSNiF_DataGenerator(channel_name = channel_name, n_neighbours = n_neighbours, n_iter = n_iter)
> generated_patches = DataGenerator.generate_patches_from_directory(load_directory = Raw_directory)
> if DataGenerator.save_patches(generated_patches, save_directory = Save_directory):
>     print('Data generated successfully!')
> ```

Hello,

Thanks for your interest in our package. I will try to solve this problem and reply to you ASAP.

Best regards.

**Comment by arcolombo** [comment]
Ok for clarity i am trying to reproduce the demo. I have downloaded the supplementary table 5 data and changed the raw inc directory to point to thw images in the zenodo.  Do we point to the OME tiff directory? Or   Thank you

**Comment by PENGLU-WashU** [comment]
> Ok for clarity i am trying to reproduce the demo. I have downloaded the supplementary table 5 data and changed the raw inc directory to point to thw images in the zenodo. Do we point to the OME tiff directory? Or Thank you
```
if 'generated_patches' in globals():
    del generated_patches
    
channel_name = "144Nd"
Raw_directory = "C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset" # change this directory to your Raw_image_directory.

Save_directory = None

n_neighbours = 4 # Larger n enables removing more consecutive hot pixels. 
n_iter = 3 # Iteration number for DIMR

DataGenerator = DeepSNiF_DataGenerator(channel_name = channel_name, n_neighbours = n_neighbours, n_iter = n_iter)
generated_patches = DataGenerator.generate_patches_from_directory(load_directory = Raw_directory)
if DataGenerator.save_patches(generated_patches, save_directory = Save_directory):
    print('Data generated successfully!')
```
Hello,

Could you please try the code above? I just changed the folder name and deleted "local-implementation-test". Please let me know if it works.

Best regards.

**Comment by arcolombo** [comment]
hi so this is resolved.

previously,  I am using windows 10, i used WSL2 , and under WSL2, i created the conda environment for  IMC DeNoise.    i think the issue is that the path directories are different under WSL.

i installed  this software without WSL, using Anaconda prompt on my main system and this worked just fine!

```Image data loaded from ...

C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\F_r1\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527528\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527529\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527530\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527531_r2\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527534\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527535\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527536\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\H1527539\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\K_r3\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\K_r4\144Nd-CD14_Nd144.tiff
C:/Users/antho/Documents/GithubRepos/supplemental data/IMC_Denoise/Raw_IMC_dataset_for_training_supp_table5/Raw_IMC_dataset\L\144Nd-CD14_Nd144.tiff

Image data loading completed!
The generated patches augmented.
The generated patches shuffled.
The generated training set with shape of (18608, 64, 64) is saved as C:\Users\antho\Documents\GithubRepos\IMC_Denoise\Jupyter_Notebook_examples\Generated_training_set\training_set_144Nd.npz.
Data generated successfully!
```

**Comment by arcolombo** [comment]
this issue is that using WSL the path names are different, resolved when using Anaconda per the installation directions.
