### ISSUE TITLE
Softplus activation function compatible for subsequent data normalisation?

### ISSUE THREAD

**Issue by BonoC** [PENGLU-WashU/IMC_Denoise#12]
Hi,

Great work on the development of DIMR and DeepSNiF for noise removal on IMC data. In the article, it says that the final layer of the U-Net uses softplus as it's activation function (log(1+exp(x))), which I believe this means that the denoised images will be log-transformed. On this basis, do I have to perform normalisation (percentile-method) on the pixel values prior inputting into DIMR and DeepSNiF? Or can I input raw images for DIMR and DeepSNiF, and from this, is it still suitable to perform log normalisation on the single cell data after segmentation?

These ideas might not make sense at all, as I am still relatively new to IMC data processing. Nevertheless, thanks for your help!

**Comment by PENGLU-WashU** [comment]
> Hi,
> 
> Great work on the development of DIMR and DeepSNiF for noise removal on IMC data. In the article, it says that the final layer of the U-Net uses softplus as it's activation function (log(1+exp(x))), which I believe this means that the denoised images will be log-transformed. On this basis, do I have to perform normalisation (percentile-method) on the pixel values prior inputting into DIMR and DeepSNiF? Or can I input raw images for DIMR and DeepSNiF, and from this, is it still suitable to perform log normalisation on the single cell data after segmentation?
> 
> These ideas might not make sense at all, as I am still relatively new to IMC data processing. Nevertheless, thanks for your help!

Hello,

Thanks for your kind words on our software package. The softplus activation function does not change the scale of the data. Please check the plot of this function online. In this case, the output will not be log-transformed. Therefore, after denoising, just apply the data to other developed IMC pipeline.

Regards.

**Comment by BonoC** [comment]
Hi @PENGLU-WashU,

Thanks for the clarification. I will close this issue as this has been solved. Thank you!
