### ISSUE TITLE
Demo data produces NaN loss on multiple systems

### ISSUE THREAD

**Issue by MathijsSanders** [PENGLU-WashU/IMC_Denoise#13]
Dear Peng,

We are keen to use IMC-Denoise for our IMC data. To get a feel for the tool we have downloaded and unzipped Raw_IMC_dataset_for_training_supp_table5.zip from https://doi.org/10.5281/zenodo.6533905.

IMC-Denoise installation was performed on Linux Mint 19.3 (NVIDIA GTX 3060), Ubuntu 20.04 (NVIDIA A40) and Debian 12 (NVIDIA GTX 3060 Ti) systems using the following commands:

```
conda create -n 'IMC' python=3.6
conda activate IMC
conda install -c anaconda brotlipy
conda install -c anaconda cudnn=7.6.5 cudatoolkit=10.1.243
pip install tensorflow==2.2.0 keras==2.3.1
pip install jupyter
``` 

Installation went without errors/problems on all systems. GPUs are visible in Python. We followed the Jupyter notebook IMC_Denoise_Train.ipynb. However, all 3 systems produce NaN loss values during training on the provided training data:

### One example
```
Epoch 1/50
124/124 [==============================] - 235s 2s/step - loss: nan - val_loss: nan

Epoch 00001: saving model to /home/thijs/trained_weights/weights_144Nd-CD14.hdf5
Epoch 2/50
124/124 [==============================] - 79s 634ms/step - loss: nan - val_loss: nan

Epoch 00002: saving model to /home/thijs/trained_weights/weights_144Nd-CD14.hdf5
Epoch 3/50
124/124 [==============================] - 78s 633ms/step - loss: nan - val_loss: nan

Epoch 00003: saving model to /home/thijs/trained_weights/weights_144Nd-CD14.hdf5
Epoch 4/50
124/124 [==============================] - 78s 632ms/step - loss: nan - val_loss: nan

Epoch 00004: saving model to /home/thijs/trained_weights/weights_144Nd-CD14.hdf5
Epoch 5/50
124/124 [==============================] - 78s 632ms/step - loss: nan - val_loss: nan

Epoch 00005: saving model to /home/thijs/trained_weights/weights_144Nd-CD14.hdf5
Epoch 6/50
124/124 [==============================] - 78s 632ms/step - loss: nan - val_loss: nan

Epoch 00006: saving model to /home/thijs/trained_weights/weights_144Nd-CD14.hdf5
``` 
Could you please advise how to proceed? Is it possible that there is a NaN value in the training data?

**Comment by PENGLU-WashU** [comment]
Hello,

Thanks for submitting the issue. There should be no NaN values in the training data. I think the problem might be caused by Keras. The codes were run smoothly on our multiple systems.

For now, could you please try to reduce the batch size and the learning rate and then let me know the results?

Thanks and best regards.

**Comment by RemcoHoogenboezem** [comment]
Dear all,

I have resolved the issue for our Ampere based cards (nvidia A40 and 3060ti) by using a newer version of the nvidiatoolkit, correspongding cudnn and tensorflow libraries. In the newer versions of tensorflow keras is part of tensorflow so I also altered the code slightly to use keras from tensorflow.

I have used the following code:

conda create -n 'IMC_Denoise2' python=3.6
conda activate IMC_Denoise2
conda install -c anaconda cudnn=8.1 cudatoolkit=11.2 
conda install -c anaconda brotlipy
 pip install tensorflow==2.6.0
 pip install numpy scipy matplotlib scikit-learn tifffile
 pip install jupyter notebook

Best,

Remco

**Comment by MathijsSanders** [comment]
Dear Peng,

Remco is a member of our bioinformatics core with a broad expertise of Cuda. He discovered that the older libraries could not combine well with our generation of NVIDIA (Ampere) GPUs. He solved the issue using the information provided above.

Did you test with an older generation NVIDIA GPU (e.g, NVIDIA GTX 20xx series)? That would explain the differences.

Cheers,

Mathijs

**Comment by PENGLU-WashU** [comment]
> Dear all,
> 
> I have resolved the issue for our Ampere based cards (nvidia A40 and 3060ti) by using a newer version of the nvidiatoolkit, correspongding cudnn and tensorflow libraries. In the newer versions of tensorflow keras is part of tensorflow so I also altered the code slightly to use keras from tensorflow.
> 
> I have used the following code:
> 
> conda create -n 'IMC_Denoise2' python=3.6 conda activate IMC_Denoise2 conda install -c anaconda cudnn=8.1 cudatoolkit=11.2 conda install -c anaconda brotlipy pip install tensorflow==2.6.0 pip install numpy scipy matplotlib scikit-learn tifffile pip install jupyter notebook
> 
> Best,
> 
> Remco

Dear all,

Thanks for your work to solve this issue. Our NVIDIA GPU is Quadro RTX 6000. The difference of GPU should be issue. 

Would you please start a pull request to our package so that you can add the modifications in our readme file? Then I can merge the requests. In this case, I will give the credit for solving this bug?

Best regards,
Peng

**Comment by PENGLU-WashU** [comment]
> Dear Peng,
> 
> Remco is a member of our bioinformatics core with a broad expertise of Cuda. He discovered that the older libraries could not combine well with our generation of NVIDIA (Ampere) GPUs. He solved the issue using the information provided above.
> 
> Did you test with an older generation NVIDIA GPU (e.g, NVIDIA GTX 20xx series)? That would explain the differences.
> 
> Cheers,
> 
> Mathijs

The problem has been solved as above.

**Comment by LukasHats** [comment]
I am also having issues with NaNs so I changed the cudNN and cudatoolkit versions. However Then tensorflow throws errors as posted in my other issue post: https://github.com/PENGLU-WashU/IMC_Denoise/issues/25


Following this suggestions:

> Dear all,
> 
> I have resolved the issue for our Ampere based cards (nvidia A40 and 3060ti) by using a newer version of the nvidiatoolkit, correspongding cudnn and tensorflow libraries. In the newer versions of tensorflow keras is part of tensorflow so I also altered the code slightly to use keras from tensorflow.
> 
> I have used the following code:
> 
> conda create -n 'IMC_Denoise2' python=3.6 conda activate IMC_Denoise2 conda install -c anaconda cudnn=8.1 cudatoolkit=11.2 conda install -c anaconda brotlipy pip install tensorflow==2.6.0 pip install numpy scipy matplotlib scikit-learn tifffile pip install jupyter notebook
> 
> Best,
> 
> Remco

I updated my tensorflow to 2.6, which gave me these errors:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imc-denoise 0.0.0 requires keras==2.3.1, but you have keras 2.10.0 which is incompatible.
imc-denoise 0.0.0 requires tensorflow==2.2.0, but you have tensorflow 2.6.0 which is incompatible.
Successfully installed absl-py-0.15.0 cached-property-1.5.2 clang-5.0 flatbuffers-1.12 gast-0.4.0 h5py-3.1.0 keras-2.10.0 six-1.15.0 tensorboard-2.10.1 tensorboard-data-server-0.6.1 tensorflow-2.6.0 tensorflow-estimator-2.8.0 typing-extensions-3.7.4.3 wrapt-1.12.1
(IMC_Denoise2) [hd_bm327@o06c02(Singularity) src]$ 
```

Also running the script completely fails because tensorflow does not match the required version from IMCDenoise.

```
Traceback (most recent call last):
  File "/gpfs/bwfor/work/ws/hd_bm327-myeloma_standal_ws/src/IMC_Denoise_Steinbock.py", line 11, in <module>
    from IMC_Denoise.IMC_Denoise_main.DeepSNiF import DeepSNiF
  File "/gpfs/bwfor/work/ws/hd_bm327-myeloma_standal_ws/src/IMC_Denoise/IMC_Denoise/IMC_Denoise_main/DeepSNiF.py", line 9, in <module>
    from keras import optimizers
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/__init__.py", line 20, in <module>
    from keras import distribute
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/distribute/sidecar_evaluator.py", line 22, in <module>
    from keras.optimizers.optimizer_experimental import (
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/optimizers/__init__.py", line 26, in <module>
    from keras.optimizers.legacy import adadelta as adadelta_legacy
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/optimizers/legacy/adadelta.py", line 17, in <module>
    from keras.optimizers.optimizer_v2 import adadelta
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/optimizers/optimizer_v2/adadelta.py", line 21, in <module>
    from keras.optimizers.optimizer_v2 import optimizer_v2
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 26, in <module>
    from keras import initializers
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/initializers/__init__.py", line 22, in <module>
    from keras.initializers import initializers_v2
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/initializers/initializers_v2.py", line 23, in <module>
    from keras.dtensor import utils
  File "/home/hd/hd_hd/hd_bm327/.conda/envs/IMC_Denoise2/lib/python3.6/site-packages/keras/dtensor/__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api
ImportError: cannot import name 'dtensor'
```
 I am anyway surprised that such an old tensorflow version was used for this algorithm. I think The package needs a huge update to the current versions of Tensorflow, otherwise these GPU problems will persist.
