### ISSUE TITLE
IMC Denoising is too aggresive for certain channels

### ISSUE THREAD

**Issue by rjesud** [PENGLU-WashU/IMC_Denoise#14]
Hi, 

Thanks very much for releasing this tool. It is proving to be very useful for our projects. For the majority of markers, the denoising performs nicely with the default parameters. However, in a channel where the majority of the field is true positive pixels, I see the the denoising actually erodes some of the real signal. 

Raw: 
![image](https://github.com/PENGLU-WashU/IMC_Denoise/assets/46010245/9443b003-71df-4c91-a8aa-21674d1e509b)

Denoised (Default parameters, color scale is same as above):
![image](https://github.com/PENGLU-WashU/IMC_Denoise/assets/46010245/6482782c-b812-45e0-8adf-9ea69dfc2851)

Do you have any suggestions for optimization of the denoising procedure for this particular issue?

**Comment by PENGLU-WashU** [comment]
Hello,

Thanks for your interest in our software package! According to my experience, there should not exist signals being eroded. Could you please tell me the training patch numbers?

Best regards

**Comment by rjesud** [comment]
![image](https://github.com/PENGLU-WashU/IMC_Denoise/assets/46010245/08cfcae9-8368-43b9-8161-d8e5f90fbce9)

This is generated from 4 images.

**Comment by PENGLU-WashU** [comment]
This is weird. In normal cases, these patches are sufficient to generate good results. I suggest at least 100 epoches for training. If the results are still not ideal, would you like to share some data with me so I can figure it out? Thanks.

**Comment by rjesud** [comment]
Hi @PENGLU-WashU, I actually trained for 250 epochs. All the other paramters were same as the tutorial notebook. Apologies, I missed that. I am attaching the channel in question. 

[Metal001_Marker.zip](https://github.com/PENGLU-WashU/IMC_Denoise/files/11807339/Metal001_Marker.zip)

**Comment by PENGLU-WashU** [comment]
Thanks for the sharing. I will try to see if it works with this one image.

**Comment by PENGLU-WashU** [comment]
> Hi @PENGLU-WashU, I actually trained for 250 epochs. All the other paramters were same as the tutorial notebook. Apologies, I missed that. I am attaching the channel in question.
> 
> [Metal001_Marker.zip](https://github.com/PENGLU-WashU/IMC_Denoise/files/11807339/Metal001_Marker.zip)

Hello,

I just used this image as the training set and trained for 100 epoches. I set the parameter "ratio_thresh" as 0.98 so that enough patches for training. (In my case, there are 2448 patches). I have attached the predicted result. I have not found bias. Please check it and let me know any problems.

Best regards 

[Metal001_Marker.zip](https://github.com/PENGLU-WashU/IMC_Denoise/files/11812360/Metal001_Marker.zip)

**Comment by rjesud** [comment]
@PENGLU-WashU 

Thank you. This looks much better. 

Is it correct to say that increasing the 'ratio_thresh' parameter incorporates more patches since we include patches that have a large percentage of "background" pixels? 

Except for processing time, do you see any other disadvantages of keeping this parameter at a higher value across channels to include more patches?

**Comment by PENGLU-WashU** [comment]
For the first question: yes, I think so.

For the second question: For now, I have not found any disadvantages except too many patches for a long-time training. However, including too many background patches might results in the ratio of signal decrease. According to my experience, around 10,000 patches for training should be good enough.

**Comment by rjesud** [comment]
Thank you for this explanation and support with this issue! I will close this ticket.
