### ISSUE TITLE
Issue generated patches from MIBI-TOF tiff data

### ISSUE THREAD

**Issue by reemabaskar** [PENGLU-WashU/IMC_Denoise#16]
Hey! Thank you for the great paper and package, I am keen to try this on my MIBI data. Unfortunately I get empty arrays when running the generate_patches_from_directory function. Images load okay but all values are changed to 0 at this step: patch_collect_sub = self.__extract_patches_from_img__(Img_DIMR, Row_range, Col_range)

The data is 1024x1024 and I get this output array([], shape=(0, 64, 64), dtype=float32)

Thank you so much for your help, I would appreciate any tips on running this type of data. Thanks!

**Comment by PENGLU-WashU** [comment]
Hello, 

Thanks for your interest in our package! Could you please indicate the format of your data? Is it tiff image?

If it is okay, could you please share an image with me so that I can find where the problem is?

Best regards

**Comment by reemabaskar** [comment]
Hey @PENGLU-WashU! Thank you for your response! Yes they are tiff images that are 1024x1024, and here is also the notebook I used to debug it to this line of code within generate_patches function: patch_collect_sub = self.extract_patches_from_img(Img_DIMR, Row_range, Col_range)
And I have attached 1 FOV as well, thank you so much and looking forward to your reply. 

[2022-12-03T15-18-19_BIGFISH1_pA_s1_R1C1.zip](https://github.com/PENGLU-WashU/IMC_Denoise/files/12639970/2022-12-03T15-18-19_BIGFISH1_pA_s1_R1C1.zip)
[IMC_Denoise_Train_and_Predict_MIBIexample.html.zip](https://github.com/PENGLU-WashU/IMC_Denoise/files/12639972/IMC_Denoise_Train_and_Predict_MIBIexample.html.zip)

**Comment by PENGLU-WashU** [comment]
Hello! I just checked the images. Are these images the raw files? The images should be denoised before normalization. In that case, the range of the images is beyond [0,1]. Hope these can help.

**Comment by reemabaskar** [comment]
Hey @PENGLU-WashU ah that's totally fair, it works on raw data! Sorry for my confusion and thank you for your help!
