### ISSUE TITLE
multi markers training

### ISSUE THREAD

**Issue by Yuanqqqqqq** [PENGLU-WashU/IMC_Denoise#17]
Hi,

I am interested in using the DIMR and DeepSNiF algorithms for my IMC data. I'd like to ask if the result is the same if I did training using a single marker or multi markers such as 30 or 40 markers?

Best regards

**Comment by PENGLU-WashU** [comment]
Hi,

Thanks for your interest in our software package. We think it will work when training for multiple markers together. However, we recommend to train each marker separately for faster training and less memory usage.

Best regards

**Comment by Yuanqqqqqq** [comment]
Hi @PENGLU-WashU ， Thanks for the reply!
