### ISSUE TITLE
About the issue of GPU usage efficiency

### ISSUE THREAD

**Issue by handong369** [PENGLU-WashU/IMC_Denoise#18]
Hello, your work is very excellent, but I have encountered a problem when conducting experiments using your code. I found that the GPU utilization is not high when running the code, and most of it is being used by the CPU. The GPU efficiency is shown in the image.

<img width="440" alt="image" src="https://github.com/PENGLU-WashU/IMC_Denoise/assets/36852077/8a9de954-b4e0-4012-bdd5-6a0643ac2c4b">

**Comment by PENGLU-WashU** [comment]
Hello, 

Thanks for your valuable findings! Could you please modify the structure or give any suggestions? Then we can merge your code.

Best

**Comment by handong369** [comment]
In the environment configuration, some improvements can be made. CUDA and corresponding CUDNN need to be installed.

**Comment by PENGLU-WashU** [comment]
Thanks. We will modify the package
