### ISSUE TITLE
Percentage of masked pixels 

### ISSUE THREAD

**Issue by rahilgholami** [PENGLU-WashU/IMC_Denoise#19]
Hi,

Thank you for your great work. I'm curious about the percentage of masked pixels in each patch—specifically, the rationale behind 0.2% (~8 pixels within a 64x64 patch). Any insights you can share on this?

Kind regards,
Rahil

**Comment by PENGLU-WashU** [comment]
Hi Rahil,

Thanks for your interest in our software package. The masking strategy in our algorithm is modified from Noise2Void (https://openaccess.thecvf.com/content_CVPR_2019/html/Krull_Noise2Void_-_Learning_Denoising_From_Single_Noisy_Images_CVPR_2019_paper.html). Please refer to this paper for more details.

Specifically, in each step during the training process, we randomly select 8 pixels from each patch. Therefore, all the pixels in each patch should be captured after the training. You can absolutely increase the sampling rate and the patch size (for example, 1% rate and 128x128 pixels). 

Please let me know if you have more questions. 

Best

**Comment by rahilgholami** [comment]
Thanks for getting back to me and your explanation. I'm curious about the sampling rate limitations. Have you ever experimented with different rates for e.g. 64x64 patches and observed any interesting effects?

**Comment by PENGLU-WashU** [comment]
Hi Rahil,

Yes I have tried different sampling rates. However, the rate should not be too large, because the masked pixel will learn information from its neighbours. When increasing the rate, I have not observed obvious enhancement regarding the image quality. Therefore, I recommend the rate set from 0.2% to 2%.

Best

**Comment by rahilgholami** [comment]
Thanks for your insightful comment!
