### ISSUE TITLE
Question about how to train DeepSNiF properly & integration with steinbock

### ISSUE THREAD

**Issue by BenCaiello** [PENGLU-WashU/IMC_Denoise#21]
Hello!

I have started working with the package and it seems to be working well so far! It looks like it could be very helpful for my work.
I was wondering two things:

1. How should DeepSNiF typically be trained? For a given experiment, I had just been training fresh for each new experiment with patches generated from the entire experiment / all ROIs -- which means a lot of patches and can take a long time for a large experiment -- and then denoising the experiment. This seems not correct to me, although the output appears to be working well. Is it more typical to choose a subset of images from an experiment and train on those, then denoise the rest of the images from the experiment? Or is it more usual to train a single version of DeepSNiF, save the weights, and then re-use that trained model for multiple experiments?

2.  I have been analyzing .mcd files and IMC images using the steinbock docker pipeline from the Bodenmiller lab, which produces a single folder with multi-channel .tiff files. This files structure, of course, does not work with how y'all originally designed with package. I have successfully modified the DeepSNiF_DataGenerator.py script and one of the example jupyter notebook file to be able to take in multi-channel tiffs housed in a single file folder for training (as steinbock outputs), then denoise selected channels, and finally export updated multi-channel tiffs with the selected channels replaced with the denoised output. Would you be interested adding this functionality into IMC_denoise? The edits required seem to be fairly small, and while my jupyter notebook script is only designed to do the whole-dataset-training-then-denoise method I have been employing, that is easily changed. I'd be happy to share my scripts / edits if you like!

**Comment by PENGLU-WashU** [comment]
Hello, thanks for your interests in the package!

Here is my reply:

1. Typically, individual markers should be trained separately except the images have similar SNR. For the same marker, you can just select parts of the images for training, but do not forget to check whether the denoising results can work well on the rest of the images. Once you have trained for one marker and saved it, normally you can use the trained model on your new data.

2. Thanks for your work! You can fork our package and I will merge it later if it works well!

Please let me know if you have any more questions.

**Comment by BenCaiello** [comment]
OK! It sounds like there are multiple options for how to train the model, just so long as the output and time required to run is acceptable to the user. I'll definitely look into training on only a few images in a dataset instead of the whole thing to same time! 
I currently don't have access to a workable gpu so saving time on training is definitely of interest to me, as long as the quality of denoising is not reduced too much.

I will create a fork and a pull request!

**Comment by LukasHats** [comment]
I would really appreciate a good integration that could work with Steinbock pipeline outputs. I am currently working with 90 IMC samples, therefore this would make my work much easier.
If the 90 samples were derived from same type of tissue, different patients, different acquisition time points, would you recommend training using all samples and use the model for denoising every sample? Doing it individually would be quite a lot of work. Thanks in advance!

**Comment by PENGLU-WashU** [comment]
> I would really appreciate a good integration that could work with Steinbock pipeline outputs. I am currently working with 90 IMC samples, therefore this would make my work much easier. If the 90 samples were derived from same type of tissue, different patients, different acquisition time points, would you recommend training using all samples and use the model for denoising every sample? Doing it individually would be quite a lot of work. Thanks in advance!

Hi,

I think it works to train the 90 samples together for each marker. Since each channels shares similar features, it does not matter that they are captured at different time.

Please test and check whether the results are good and let me know if you have any more questions.

Thanks!

**Comment by BenCaiello** [comment]
Have you had a chance to look at my proposed edit to the package + jupyter notebook script for integrating steinbock with IMC_Denoise? It has been working quite well on what data I have tested it on so far!
Although, I may want to add a bit of code to allow it to output .ome.tiff formatted files, since my current script creates .tiff files that are not readable by QuPath, if someone (like me!) wanted to have access to that option after denoising.

The edits also \<should\> not cause issues for the rest of the package, as the code chunk that is added to the DeepSNIF_DataGenerator.py script to allow it to ingest multi-channel .tiffs is locked behind an if statement that only runs if the user intentionally calls it by passing a new attribute into the DataGenerator (the default behavior is still set to reading single-channel .tiffs, so nothing should break).

Also, for training, I tested how it would work with various % of the data set as the original training dataset -- I don't have a strong enough GPU to use CUDA with this, and the training takes a long time, so shrinking the training data can be useful. It seems to work pretty well training on only 50% of a small dataset (if I recall correctly, 5 out of 10 total images) to denoise all the images in the dataset, so IMC_Denoise's performance might be pretty robust even with less than "ideal" training inputs.

**Comment by LukasHats** [comment]
Yes, I already looked into your repo and will try this out if the time comes. I am dealing with uncompensated IMC data and still have to figure out how to check for the spillover and SNR (I guess the best way is FCS files and just checking in FlowJo). But so far I still need to produce these fcs files...
So if there is significant spillover or bad SNR I will give it a try. I would also prefer ome.tif format! But that will need a very careful setup of the XML environment. And if you have any suggestions on how to check for spillover and SNR and generate fcs, it's more than welcome. And thanks for the repository that merges Steinbock and Denoise. Just be aware that I had trouble dealing with the ome.tif generated by Steinbock, I could not use it in MCMICRO because of metadata issues.

**Comment by BenCaiello** [comment]
To get .fcs quick & easy, just drag the intensity .csv's from steinbock into a FlowJo window -- FlowJo does automatic conversions to .fcs from .csv . The files will show up in the same folder as the .csv's. I'd been used that trick to get the steinbock files into an .fcs-based analysis pipeline, although more recently I've started exploring using python to automate it.

Does steinbock have an export .ome.tiff option? When I've run the docker container of steinbock, I've only seen plain tifs get produced.

As for SNR, I haven't really been focusing on that question in part because I work in a shared resource facility, not in an individual lab, so my goal is to set up a pipeline to benefit of our users (hopefully with an option to denoise), and not for my own research projects. Also, I've mainly been doing the denoise on segmentation channels without looking too closely at pre-denoise SNR, as the primary question is whether the denoised channel itself & especially the segmentation masks appear better / worse than without denoising. So far, the segmentation with deepcell has usually looked better after denoising. 
Of note though, while I know denoising should be used with caution since it loses information from images and can take a long time with training, my limited experience is that IMC denoise output still looks alright even when it is used on channels that have high SNR (like DNA channels for segmentation).

**Comment by LukasHats** [comment]
Dear Ben,

awesome I did not know about that feature from FlowJo! That helps a lot!
Yes Steinbock has that Option, just produce the tiff files with `steinbock preprocess imc images --hpf 50` and then run `steinbock export ome` it will create an ome folder with all images in the ome format.

And thanks for your input on denoising, as I also used MESMER for segmentation and with bone marrow it gets quite ugly, so I will definitely try to denoise then. Are you by default denoising every channel? If you want to talk on a different plattform, feel free to contact me via e.g. twitter [@LukasHats](https://twitter.com/LukasHats) .Our Dicussion was so helpful!

**Comment by LukasHats** [comment]
Dear Ben,

how do you handle the hot pixels? With DIMR, IMC Denoise has its own algorithm for removing them, so I would probably skip the `--hpf` option for `steinbock preprocess imc images` right? But does that mean you are using it on all channels, as hot pixel filtering has to be done on every image I would suppose.

**Comment by LukasHats** [comment]
And by the way, you hard coded the image paths for windows, that causes problems with mac users and linux. E>g. hard coding the path with \\\ is not working for max and windows.

**Comment by BenCaiello** [comment]
Glad that the FlowJo trick is helpful!
This discussion has quite useful for me as well! I am fairly new to coding, so it is good learn the differences between windows / linux /mac. I also know that windows isn't very common in data science, so I'm hoping to try using the other OS options eventually

 *For fixing it, isn't it true that I could replace the escaped backslash '\\' separator with '/' forward slash and have it work in linux / mac?*


That should be an easy fix, although if it doesn't work I can use learn to use the Path / os modules like a normal person. 
Let me know if there are any other oddities in my coding!

For DIMR vs. hpf, I not sure how much it matters if you use one or the other or both, since they effectively do the same thing. I'd just pick one / both options and roll with it. There are only so many hot pixels to process, and once they are removed by one algorithm, the other algorithm shouldn't touch those same pixels again since they aren't hot anymore (although it may process additional pixels not picked up by the first). 

When I have used IMC_denoise for segmentation, I have been denoise all segmentation channels -- but that might not be necessary.

**Comment by LukasHats** [comment]
Yes, that's the quick fix I used. However as you also did a pull request, this has to be fixed. Best practice would be to write it in a way so everyone can use it. It should be a quick fix, e.g. just use ChatGPT4 for it, that should give you a fast workaround. I will have to run it on our HPC to see if everything works.
Just for better handling, I would also propose that you transform it into a .py file and use the argparse library to make it usable from the CLI. I will do that anyway so I can use it easily on our HPC. If you want, I can provide you the code for it once I am finished. Its not a big problem.

**Comment by BenCaiello** [comment]
I've just replaced the '\\\\' with '/' in my pull request repo (both in the notebook & in the DataGenerator file) -- I am about to test it on my windows system again, but this should be compatible with all systems, correct?

Ah, it is easier for you to run from .py files instead of a notebook? I'll have to consider that then going forward.

**Comment by LukasHats** [comment]
I don't know, a file path in mac should use '/'. You will have to check if it still works if you remove it.

It depends, a jupyter notebook is good for exploring data, but if you want to run stuff e.g. on a high-performance cluster, it is easier to have a .py file and input the arguments from CLI. That's why I will create a CLI for your script. Normally this is co-development, which should be done via GitHub and forking and branching and pulling :D But yeah I will consider forking your repo and adding the cli script.

**Comment by BenCaiello** [comment]
Forward slashes work on windows, too, so I should just use those or Pathlib going forward since they work with all systems. That's also interesting and good know about CLI for higher performance. Thanks!

**Comment by LukasHats** [comment]
I just provided a pull request with my CLI script. It just handles the most important parameters, I also fine-tuned your jupyter NB.

**Comment by BenCaiello** [comment]
Cool, that looks awesome! Is it working well for your data analysis then?

**Comment by LukasHats** [comment]
I am trying it out, it took me the whole day to figure out what went wrong. The old cudNN and cudatoolkit and tensorflow libraries do not work with newer GPUs as the ones from our cluster. I therefore had to change a few files so it works with tensorflow 2.6. It now finally runs on our GPU. 
see here: https://github.com/PENGLU-WashU/IMC_Denoise/issues/25

I tracked all changes I made for tensorflow 2.6 in a branch of the forked directory so I can open a pull request once Peng wants to open a branch that works with tensorflow 2.6.

**Comment by LukasHats** [comment]
Dear @BenCaiello. I just finished running on our HPC cluster and saw, that the channels were all the same after denoising except the last one using this:

```
for channel in range(image1.shape[0]):
    channel1 = image1[channel,:,:]
    channel2 = image2[channel,:,:]
    if np.array_equal(channel1, channel2):
        print(f"Channel {channel}: All pixels are the same.")
    else:
        print(f"Channel {channel}: Pixels differ.")
```

 I went back to your Steinbock Jupyter notebook and concerning this snippet:
 
```
for i in channel_names:
    n_neighbours, n_iter, window_size, train_loss, val_loss, deepsnif = DeepSNiF_train(i)
    for img in os.listdir(Raw_directory):
        img_path = os.path.join(Raw_directory, img)
        with tp.TiffFile(img_path) as tif:
            Img_raw = tif.pages[i].asarray()
        Img_DIMR_DeepSNiF = deepsnif.perform_IMC_Denoise(Img_raw, n_neighbours = n_neighbours, n_iter = n_iter, window_size = window_size)
        numpy_tiff = tp.imread(img_path)
        numpy_tiff[i] = Img_DIMR_DeepSNiF
        tp.imwrite(os.path.join(output_directory, img),numpy_tiff, photometric='minisblack')
    #This if statement for cases when you are running multiple channels at once and not overwriting the /img folder. It ensures the first N channels you denoise are not overwritten when denoising channel N+1.
    if Raw_directory != output_directory:
        Raw_directory = output_directory

```

For my script I erased the last two lines which results in the script always importing fresh images and in the last for loop step only the last channel gets changed. The way your script is hard coded and kind of confuses with overwriting directories is really confusing. I would suggest using temporary directories as in my script. I will open a new pull request with updated versions to make it a bit more pythonic and less confusing.

```
# Iterate through each image in the Raw_directory
for img in os.listdir(Raw_directory):
    img_path = os.path.join(Raw_directory, img)

    # Attempt to open and read the TIFF file once per image
    try:
        with tp.TiffFile(img_path) as tif:
            numpy_tiff = tif.asarray()  # Read the entire stack once

        # Check if the TIFF file has multiple pages/channels
        if numpy_tiff.ndim < 3:
            print(f"Skipping {img}, as it does not contain multiple channels.")
            continue

        # Perform denoising for each specified channel
        for i in channel_names:
            n_neighbours, n_iter, window_size, train_loss, val_loss, deepsnif = DeepSNiF_train(i)
            Img_raw = numpy_tiff[i, :, :]  # Access the specific channel
            Img_DIMR_DeepSNiF = deepsnif.perform_IMC_Denoise(Img_raw, n_neighbours=n_neighbours, n_iter=n_iter, window_size=window_size)
            numpy_tiff[i, :, :] = Img_DIMR_DeepSNiF  # Update the channel in the array

        # Write the updated numpy array back to a TIFF file
        tp.imwrite(os.path.join(temp_output_dir, img), numpy_tiff, photometric='minisblack')

    except Exception as e:
        print(f"Error processing {img}: {e}")
        continue
```

@PENGLU-WashU  I will submit a pull request to update my script

Best,
Lukas

**Comment by BenCaiello** [comment]
Might it be in how you separated the denoising loop from the temporary directory handling?
As in, the temporary directory handling is not inside the loop:

```
# This loop iterates through the list of channels and performs DIMR + DeepSNiF on each:
for i in channel_names:
    n_neighbours, n_iter, window_size, train_loss, val_loss, deepsnif = DeepSNiF_train(i)
    for img in os.listdir(Raw_directory):
        img_path = os.path.join(Raw_directory, img)
        Img_raw = tp.TiffFile(img_path).pages[i].asarray()
        Img_DIMR_DeepSNiF = deepsnif.perform_IMC_Denoise(Img_raw, n_neighbours = n_neighbours, n_iter = n_iter, window_size = window_size)
        numpy_tiff = tp.imread(img_path)
        numpy_tiff[i] = Img_DIMR_DeepSNiF
        tp.imwrite(os.path.join(temp_output_dir, img), numpy_tiff, photometric='minisblack')

# If a temporary directory was used, move the processed files back to the original directory
if Raw_directory == output_directory:
    for img in os.listdir(temp_output_dir):
        shutil.move(os.path.join(temp_output_dir, img), os.path.join(Raw_directory, img))
    # Remove the temporary directory
    shutil.rmtree(temp_output_dir)
# Steinbock should now be able to seemlessly work with the denoised files
```

Like you saw, my original script handled the overwriting slightly differently yours -- with no temporary directory -- in the case the input directory == output directory it just directly overwrites the files each cycle which preserves any changes you make to the images each loop and runs into no problems.
The edge case when overwriting without a temp directory like this is now instead when your output is *different* than the input, since the changes you make each loop in the output aren't carried forward into the next loop from the input, and get overwritten.
My solution was meant to solve this by, after the first loop, reverting to the well-behaved direct overwriting behavior I had been accustomed to with this code snippet:

```
        if Raw_directory != output_directory:
                Raw_directory = output_directory
```
Your solution with a temporary directory also works, I think, but the key should be when the handling of this issue occurs: it ought to happen inside the loop, not at the end. 

So to fix your original code, I suspect it would only require indenting the block starting with 
``` if Raw_directory == output_directory: ```
so that the temp directory copying runs after each denoising loop, since then you'd be updating the input folder with your desired denoised output, which would carry over into the next copying cycle, etc. 

As to looping through the images first, then the channels -- that should work if you want to denoise each image separately, but I think it would cause some issues if you are trying to train the algorithm on the whole dataset first?
Since in that case you want to retrieve all fields of view of the same channel in the dataset at once, then train DeepSNiF on that larger dataset. That whole dataset training was what I was aiming for, so that is probably why I did channel first.

**Comment by LukasHats** [comment]
Ah you are right, I am now training on the whole dataset for each image separately. I will change it again. But will think of a better way to handle directories. You were right! THanks for the heads up

**Comment by LukasHats** [comment]
I came up with something different, so we store each trained model in a dictionary first and elegantly use it later while looping through images:

```
# Train a model for each channel and store it
trained_models = {}
for i in channel_names:
    n_neighbours, n_iter, window_size, train_loss, val_loss, deepsnif = DeepSNiF_train(i)
    trained_models[i] = deepsnif  # Store the trained model for later use


# Iterate through each image in the Raw_directory
for img in os.listdir(Raw_directory):
    img_path = os.path.join(Raw_directory, img)
    # Load the entire multi-channel image once
    numpy_tiff = tp.imread(img_path)

    # Process each specified channel using the pre-trained models
    for i in channel_names:
        deepsnif = trained_models[i]  # Retrieve the trained model for this channel
        Img_raw = numpy_tiff[i]  # Work directly with the loaded numpy array
        Img_DIMR_DeepSNiF = deepsnif.perform_IMC_Denoise(Img_raw, n_neighbours=n_neighbours, n_iter=n_iter, window_size=window_size)
        numpy_tiff[i] = Img_DIMR_DeepSNiF  # Update the channel in the numpy array

    # Write the fully denoised image to the output directory after all channels have been processed
    tp.imwrite(os.path.join(temp_output_dir, img), numpy_tiff, photometric='minisblack')

# If a temporary directory was used, move the processed files back to the original directory
if Raw_directory == output_directory:
    for img in os.listdir(temp_output_dir):
        shutil.move(os.path.join(temp_output_dir, img), os.path.join(Raw_directory, img))
    # Remove the temporary directory
    shutil.rmtree(temp_output_dir)
```

**Comment by BenCaiello** [comment]
Great! That should solve the issue. 

I am wondering though -- is there a specific reason why you don't favor the script directly overwriting files as it goes and choose to use a temporary directory method instead? As far as I can tell, the difference between the two strategies doesn't change the behavior of the program in terms of output. 
The only major differences I see would be that now the script will have a slightly different order, training on all channels, then processing each image, as opposed to training and processing 1 channel at a time + the final temporary --> output directory file copying. Is there a general advantage in not directly overwriting files / using temporary directories that makes them "good practice" when coding programs like these?

**Comment by LukasHats** [comment]
Not that I can think of. But in terms of reproducibility and readability for others who might want to contribute, it is better to create temporary folders than overwrite the directories. But thanks for pointing me towards that, you even wrote the reason in the script but I was blind.

However when looking at the GPU efficiency it looks like it is way better now that training is separated:

```
Thu Apr 11 22:33:56 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A40                     On  | 00000000:01:00.0 Off |                    0 |
|  0%   58C    P0             172W / 300W |   5556MiB / 46068MiB |     47%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    613693      C   python                                     5544MiB |
+---------------------------------------------------------------------------------------+
bash-4.4$ 
```

**Comment by CharlesARoy** [comment]
Hey guys,

Great discussion! And thanks for all the work you put into creating IMC_Denoise and adding the ability to handle Steinbock inputs more easily!

I am currently working on creating a somewhat more seamless pipeline to stitch together Steinbock, IMC_Denoise, and the Bodenmiller R-based [IMC Data Analysis Workflow](https://bodenmillergroup.github.io/IMCDataAnalysis/index.html) for a collaborator. As I was getting up to speed on IMC_Denoise, I noted a few areas for improvement (#38) in the current repo that would probably help other users if addressed. Just wanted to note it here since several of my suggestions relate to the code @LukasHats and @BenCaiello prepared.

Otherwise, I have a few outstanding questions for @PENGLU-WashU (or any of you). Here's what I'm wondering:
1. @PENGLU-WashU, in response to Ben, you mentioned that:
> normally you can use the trained model on your new data

Under what circumstances would it be best practice to retrain the model? For example, what if the same marker/channel is used but the tissue type changes? Or what if the same marker/channel is used, but the sample is prepared by a different facility? Etc. Any guidance here is appreciated!

2. If it makes sense to do this, my goal is to train a model as thoroughly as possible for each marker/channel and then just keep reusing those models for their respective markers/channels indefinitely. If that approach seems reasonable to you, what is the best way to achieve a maximum quality (but not overfit) model? My instinct would be to use a large amount of training data, a "normal" `--network_size`, a high number of epochs (e.g., 400), and maybe a slow learning rate? Does this sound about right? Any suggestions here?

3. I haven't done any GPU computing before and have a few questions about the GPUs. First, are GPUs required to run the tool? If GPUs are not required, do you think this code can be parallelized to use more CPUs? And then, if one is using a GPU, do you have a rough sense of what the GPU memory requirements are for different parameters, like the size of the patches and the `--train_batch_size`?

Thanks for the help!
