### ISSUE TITLE
Image format

### ISSUE THREAD

**Issue by StiThor** [PENGLU-WashU/IMC_Denoise#5]
Hi and thanks for this exciting package! I`m trying to implement and test IMC denoise to a huge IMC dataset I`m working on. How did generate the image files that are used for the example data?

**Comment by PENGLU-WashU** [comment]
> Hi and thanks for this exciting package! I`m trying to implement and test IMC denoise to a huge IMC dataset I`m working on. How did generate the image files that are used for the example data?

Hi, thanks for testing this package! May I ask what is the format of your data? I recommend you transfer the data to ".tiff" format and save them in a folder, which is as shown in the README file. Then you can generate training set as README file shown. Please let me know if this is your problem.

**Comment by StiThor** [comment]
Do you mean the original format? In that case it's .mcd files.

**Comment by PENGLU-WashU** [comment]
> Do you mean the original format? In that case it's .mcd files.

If it is .mcd files, you can convert them to .tiff files using MCD viewer. Then put the .tiff files in folders as we recommend in the README file.

**Comment by StiThor** [comment]
Okei thanks, I will try that! Another thing am curious about: after denoise is done with Jupiter, how do I export the new .tiff image out so I can use it for downstream analysis? Do you have a code you can shear with me?

And one more question: would you say that this approach is comparable with spillover compensation? (https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html)

**Comment by PENGLU-WashU** [comment]
> Okei thanks, I will try that! Another thing am curious about: after denoise is done with Jupiter, how do I export the new .tiff image out so I can use it for downstream analysis? Do you have a code you can shear with me?
> 
> And one more question: would you say that this approach is comparable with spillover compensation? (https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html)

In the Jupyter file, we have not added the code to save the image as .tiff. However, it should be easy to save the image as .tiff with the existing library, such as "tifffile". We provide scripts to denoise a batch of images in terminal. Please refer to "python scripts/Predict_IMC_Denoise_batch.py --channel_name '141Pr' --load_directory 'raw_image_folders (please refer to Section: Directory structure of IMC_Denoise)' --save_directory 'IMC_Denoise_processed_image_folders' --weights_name 'weights_141Pr-CD38.hdf5' --weights_save_directory 'your_directory_to_save_trained_weights' --n_neighbours '4' --n_iter '3' --slide_window_size '3' " in the README file.

 This approach is to denoise the image, not to correct spillover. If severe spillover exists and the images are noisy, please denoise the images first and then use Bodenmiller's spillover correction package.
