### ISSUE TITLE
Val_loss

### ISSUE THREAD

**Issue by StiThor** [PENGLU-WashU/IMC_Denoise#6]
Hi. I`m running a 4090 RTX card with the script, but it gives me na values during Deep SNIF training. Which settings can I adjust for getting a value?

**Comment by PENGLU-WashU** [comment]
> Hi. I`m running a 4090 RTX card with the script, but it gives me na values during Deep SNIF training. Which settings can I adjust for getting a value?

Hello, may I ask both the training and validation losses are NaN? Does this happen only on a particular dataset or all of your data? Have you checked if any pixel values of your data are NaN?

**Comment by StiThor** [comment]
Hi. Yes, both values are NaN. That's the thing. I have used a dataset of 20 ROIs from IMC for doing the training. I have tried 4 different computers:

Nvidia RTX 4090 stationary - NaN values for both
Nvidia RTX 2080 super stationary  - Works great
Nvidia RTX 3070 laptop - NaN values for both
Dell computer without dedicated screen card - Works

I`m scratching my head here trying to understand what's making it not work on two of them. Could it be the "Train_initial_lr settings"? But I have made it work as I said on one good computer and I have to say that the trained data is a huge improvement to the raw data. So thanks so much for sharing IMC_Denoise package with us!

**Comment by PENGLU-WashU** [comment]
> Hi. Yes, both values are NaN. That's the thing. I have used a dataset of 20 ROIs from IMC for doing the training. I have tried 4 different computers:
> 
> Nvidia RTX 4090 stationary - NaN values for both Nvidia RTX 2080 super stationary - Works great Nvidia RTX 3070 laptop - NaN values for both Dell computer without dedicated screen card - Works
> 
> I`m scratching my head here trying to understand what's making it not work on two of them. Could it be the "Train_initial_lr settings"? But I have made it work as I said on one good computer and I have to say that the trained data is a huge improvement to the raw data. So thanks so much for sharing IMC_Denoise package with us!

Hi, I think for NaN values, you should replace them with 0. I guess because of the NaN values, the losses are NaN as well.

**Comment by PENGLU-WashU** [comment]
> Hi. Yes, both values are NaN. That's the thing. I have used a dataset of 20 ROIs from IMC for doing the training. I have tried 4 different computers:
> 
> Nvidia RTX 4090 stationary - NaN values for both Nvidia RTX 2080 super stationary - Works great Nvidia RTX 3070 laptop - NaN values for both Dell computer without dedicated screen card - Works
> 
> I`m scratching my head here trying to understand what's making it not work on two of them. Could it be the "Train_initial_lr settings"? But I have made it work as I said on one good computer and I have to say that the trained data is a huge improvement to the raw data. So thanks so much for sharing IMC_Denoise package with us!

It is our pleasure to make contributions to this community! ;)
