### ISSUE TITLE
Updating tensorflow, cudnn and cudatoolkit

### ISSUE THREAD

**Issue by StiThor** [PENGLU-WashU/IMC_Denoise#7]
Hi,

There are newer versions of tensorflow, cudnn and cudatoolkit compared to what IMC_Denoise uses. Could updating these packages in the script make the process of training go faster?

**Comment by PENGLU-WashU** [comment]
> Hi,
> 
> There are newer versions of tensorflow, cudnn and cudatoolkit compared to what IMC_Denoise uses. Could updating these packages in the script make the process of training go faster?

Hello, to the best of my knowledge, the cuda libraries or the version of tensorflow do not affect the performance too much. If you would like to accelerate your training, you could change the network structure to a smaller UNet. In that case, the performance will not drop a lot, but you should save lots of time for training.
