### ISSUE TITLE
Logics behind data preprocessing

### ISSUE THREAD

**Issue by petesfew** [PENGLU-WashU/IMC_Denoise#9]
Hi,

I am interested in using IMC Denoise to preprocess my IMC data. Particularly, I plan applying the DIMR algorithm to remove hot pixels, but am still open to options on which approach to use for background noise removal (due to absence of an NVIDIA GPU at the moment). My question is whether it it technically logical to use DIMR for hot pixel removal but to couple it with another background noise removal strategy (ie. Ilastik binary classification)? 

In addition, I was also wondering whether it is recommended to perform hot pixel filtration, background noise, and lastly spillover compensation in this order, regardless of the algorithms picked for data pre-processing. 

Thank you so much for your help!

**Comment by PENGLU-WashU** [comment]
> Hi,
> 
> I am interested in using IMC Denoise to preprocess my IMC data. Particularly, I plan applying the DIMR algorithm to remove hot pixels, but am still open to options on which approach to use for background noise removal (due to absence of an NVIDIA GPU at the moment). My question is whether it it technically logical to use DIMR for hot pixel removal but to couple it with another background noise removal strategy (ie. Ilastik binary classification)?
> 
> In addition, I was also wondering whether it is recommended to perform hot pixel filtration, background noise, and lastly spillover compensation in this order, regardless of the algorithms picked for data pre-processing.
> 
> Thank you so much for your help!

Hello, 

For the first question, I think it is reasonable to first filter hot pixels and then remove background noise.

For the second question, yes, I think it should be okay to process the data using this procedure. However, I am not sure if it is okay to do spillover compensation after using ilastik to binarize the signal.

Regards.

**Comment by petesfew** [comment]
Hi @PENGLU-WashU 

Thanks for the reply!
